name: raft-distillation-recipe
infra:
    provider: "bicep"
    path: "infra/azd"

pipeline:
  variables:
    - AZURE_OPENAI_ENDPOINT
    - AZURE_OPENAI_API_VERSION
    - AZURE_RESOURCE_GROUP
    - AZURE_OPENAI_4_EVAL_DEPLOYMENT_NAME
    - AZURE_OPENAI_DEPLOYMENT_NAME
    - AZURE_OPENAI_35_TURBO_DEPLOYMENT_NAME
    - AZURE_SEARCH_ENDPOINT
    - AZURE_OPENAI_NAME
