# yaml-language-server: $schema=ai.yaml.json

deployments:
  - name: text-embedding-ada-002
    platform: openai
    model:
      format: OpenAI
      name: text-embedding-ada-002
      version: "2"
    sku:
      name: "Standard"
      capacity: 20
  - name: Llama-3.1-405B-Instruct
    platform: serverless
    model:
      registry: azureml-meta
      name: Meta-Llama-3.1-405B-Instruct
